services:
  db:
    image: postgres:13
    container_name: postgres-cardapio
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cardapio
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
