services:
  db:
    image: postgres:13
    container_name: postgre-cardapio
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cardapio
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-cardapio
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: cardapio
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npx ts-node-dev --respawn --transpile-only src/server.ts

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-cardapio
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
